/* Contenido del acompañamiento. Completar los datos reales antes del lanzamiento. */
window.BEMA_SITE = (() => {
  const settings = {
    name: 'Bema Vita',
    provider: { name: '', bio: '', credentials: [] },
    // Enlace HTTPS real: agenda, página de contacto o WhatsApp autorizado.
    contact: { url: '', label: 'Solicitar orientación' }
  };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const services = [
    {id:'elegir-carrera', icon:'book', audience:'Preparatoria y primeros años universitarios', title:'Quiero elegir carrera', intro:'Tienes muchas opciones, pocas certezas y una decisión que parece enorme. Puedes empezar por entender qué tiene sentido para ti.', question:'¿Qué camino quiero explorar y por qué?', items:['Reconocer intereses, fortalezas, valores y motivaciones.','Comparar carreras con la realidad de sus actividades cotidianas.','Considerar tu contexto, tus oportunidades y lo que necesitas aprender.','Diseñar experiencias pequeñas antes de tomar una decisión.'], action:'Investiga tres opciones. Habla con alguien que las ejerza. Prueba una actividad relacionada.', example:'Ser bueno en matemáticas puede abrirte opciones. Tu elección también necesita considerar qué problemas disfrutas resolver y cómo quieres trabajar.'},
    {id:'desarrollo', icon:'compass', audience:'Universitarios y jóvenes profesionistas', title:'Ya elegí carrera, ¿ahora qué?', intro:'Una carrera puede contener muchas vidas profesionales. Descubre qué áreas, experiencias y formas de trabajar quieres construir dentro de ella.', question:'¿Dónde puedo desarrollarme dentro de mi profesión?', items:['Explorar especialidades, funciones y ambientes de trabajo.','Revisar qué formas de estudiar te ayudan en la práctica.','Elegir prácticas, proyectos y primeras experiencias profesionales.','Identificar habilidades que quieres desarrollar, incluso fuera de tus preferencias.'], action:'Elige dos áreas de tu profesión. Compara sus tareas reales y busca una experiencia en cada una.', example:'Dos personas que estudian medicina pueden encontrar satisfacción en caminos distintos: atención clínica, investigación, docencia, gestión o salud pública. La carrera es un inicio; tu trayectoria se construye.'},
    {id:'reorientacion', icon:'leaf', audience:'Adultos en un momento de cambio', title:'Quiero replantear mi rumbo', intro:'Puedes hacer bien tu trabajo y preguntarte si quieres seguir ahí. Dale espacio a esa pregunta y explora el cambio con información y experiencias.', question:'¿Qué quiero conservar, cambiar o explorar?', items:['Distinguir lo que haces bien de lo que quieres sostener.','Reconocer actividades que te energizan y otras que te desgastan.','Explorar nuevas funciones, sectores, proyectos o posibilidades de emprendimiento.','Considerar recursos, responsabilidades y oportunidades para una transición.'], action:'Formula una hipótesis de cambio. Pruébala con un curso, un proyecto o una conversación antes de dar un salto mayor.', example:'Quizá necesitas cambiar de profesión. Quizá necesitas otra función, otro ambiente o una forma distinta de ejercerla. El proceso te ayuda a explorar estas posibilidades.'}
  ];
  const stages = [
    ['Conocerte','Tu historia es el punto de partida.','Exploramos pensamiento, intereses, valores, motivaciones, fortalezas y experiencias que te dan energía o te desgastan.'],
    ['Interpretar','La información cobra sentido contigo.','Relacionamos los patrones con situaciones reales. Distinguimos preferencias, habilidades aprendidas y expectativas externas.'],
    ['Explorar','Una opción merece preguntas, no etiquetas.','Construimos alternativas académicas y profesionales y revisamos sus actividades, ambientes, oportunidades y exigencias.'],
    ['Probar y decidir','La claridad se convierte en acción.','Elegimos experiencias para contrastar tus hipótesis: conversaciones, cursos, proyectos o prácticas. Revisas lo aprendido y decides tu siguiente paso.']
  ];
  const faqs = [
    ['¿Una evaluación me dirá exactamente qué carrera estudiar?','No. Las herramientas ayudan a reconocer patrones y abrir preguntas. La elección también considera tus intereses, habilidades, valores, contexto, oportunidades y experiencia. La decisión se construye contigo.'],
    ['¿Puedo tener talento fuera de mi preferencia principal?','Sí. Una preferencia no establece el límite de tus capacidades. Puedes aprender y desarrollar habilidades; también conviene observar el esfuerzo que te cuesta sostener una actividad y la energía que te aporta.'],
    ['¿Mi perfil puede cambiar?','Tus experiencias, habilidades, intereses, circunstancias y maneras de actuar pueden cambiar. Un perfil ofrece información que puedes contrastar con tu experiencia, no una definición permanente de quién eres.'],
    ['¿Qué pasa si ya elegí carrera?','El proceso también te ayuda a explorar especialidades, funciones, ambientes de trabajo y experiencias dentro de tu carrera. Haber elegido una profesión no resuelve todas las decisiones que vienen después.'],
    ['¿Es solamente para estudiantes?','No. También está pensado para jóvenes profesionistas y adultos que están considerando una transición, un nuevo proyecto o una forma distinta de ejercer su profesión.'],
    ['¿Las guías de esta página son la evaluación Benziger?','No. Las guías disponibles son ejercicios originales y demostrativos, sin validación psicométrica. No sustituyen una evaluación formal ni el acompañamiento; sus resultados resumen tus respuestas y sirven para reflexionar.']
  ];
  const link = s => `#acompanamiento/${s.id}`;
  const cta = () => '<a class="btn" href="#primer-paso">Encontrar mi punto de partida <span aria-hidden="true">↗</span></a>';
  const serviceCards = icon => services.map(s=>`<article class="service-card"><div class="icon-circle">${icon(s.icon)}</div><p class="service-audience">${s.audience}</p><h3>${s.title}</h3><p>${s.intro}</p><a class="text-link" href="${link(s)}">Conocer este acompañamiento <span aria-hidden="true">↗</span></a></article>`).join('');
  const steps = () => `<ol class="process-grid">${stages.map(([title,short,body],i)=>`<li><span class="process-number">0${i+1}</span><h3>${title}</h3><p class="process-short">${short}</p><p>${body}</p></li>`).join('')}</ol>`;
  const faq = () => `<section class="section faq" id="faq"><p class="eyebrow">Preguntas que también tienen lugar aquí</p><h2>Lo que necesitas saber</h2>${faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section>`;
  const closing = () => `<section class="closing-band"><div><p class="eyebrow">Empieza a explorar</p><h2>Tu siguiente paso<br>empieza contigo.</h2><p>Elige tu momento y descubre por dónde empezar.</p></div>${cta()}</section>`;
  const moments = [
    {id:'elegir-carrera', icon:'book', label:'Elegir carrera', text:'Quiero descubrir qué estudiar o comparar mis opciones.', number:'01'},
    {id:'desarrollo', icon:'compass', label:'Crecer en mi profesión', text:'Ya elegí carrera. Quiero encontrar mi lugar dentro de ella.', number:'02'},
    {id:'reorientacion', icon:'leaf', label:'Cambiar de rumbo', text:'Quiero explorar otra etapa de mi vida profesional.', number:'03'}
  ];
  const momentCards = (icon, start=false) => moments.map(m=>`<a class="moment-card" href="#${start?'primer-paso':'acompanamiento'}/${m.id}"><span class="moment-top"><span class="icon-circle">${icon(m.icon)}</span><span class="moment-number" aria-hidden="true">${m.number}</span></span><h3>${m.label}</h3><p>${m.text}</p><span class="moment-action">${start?'Elegir este momento':'Ver acompañamiento'} <span aria-hidden="true">↗</span></span></a>`).join('');
  function home(icon) {
    return `<div class="container home">
      <section class="hero"><div class="hero-copy"><p class="eyebrow">Orientación vocacional y profesional</p><h1>Conocerte cambia<br>la manera en<br><em>que eliges.</em></h1><p class="lead">Comprende tus fortalezas, explora tus opciones y construye una trayectoria con sentido para ti.</p><div class="actions"><a class="btn" href="#primer-paso">Encontrar mi punto de partida <span aria-hidden="true">↗</span></a><a class="text-link" href="#proceso">Cómo funciona</a></div><p class="hero-footnote">Antes, durante y después de elegir carrera.</p></div><figure class="hero-figure"><img class="hero-art" src="assets/hero.webp" alt="Una persona con un cuaderno explora caminos hacia espacios de estudio y trabajo." width="1536" height="1024" fetchpriority="high"><figcaption>Tu historia es el punto de partida.</figcaption></figure></section>
      <section class="section moment-section"><div class="section-heading"><div><p class="eyebrow">Un acompañamiento para tu momento</p><h2>¿Dónde te encuentras hoy?</h2></div><p class="section-aside">Elige la situación que más se acerque a la tuya.</p></div><div class="grid-3">${momentCards(icon)}</div></section>
      <section class="section clarity-section"><div class="clarity-art"><img src="assets/paths.webp" alt="Dos personas conversan sobre sus opciones en un espacio de orientación cálido y luminoso." width="1536" height="1024" loading="lazy"><span class="art-label">Una carrera. Muchas posibilidades.</span></div><div class="clarity-copy"><p class="eyebrow">Claridad para decidir</p><h2>Más que elegir una carrera.<br>Aprender a construir<br>tu trayectoria.</h2><p class="muted">Puedes ser bueno en algo y querer un camino distinto. También puedes haber elegido bien tu carrera y estar buscando tu lugar dentro de ella.</p><ul class="clarity-list"><li>${icon('check')}<span>Comprender lo que te motiva y lo que necesitas.</span></li><li>${icon('check')}<span>Comparar opciones con tu historia y tu contexto.</span></li><li>${icon('check')}<span>Convertir lo aprendido en pasos que puedas probar.</span></li></ul><a class="text-link" href="#metodologia">Conocer nuestro enfoque <span aria-hidden="true">↗</span></a></div></section>
      <section class="section process-preview"><div class="section-heading"><div><p class="eyebrow">Un proceso, cuatro pasos</p><h2>De conocerte a decidir.</h2></div><a class="text-link" href="#proceso">Ver el proceso completo <span aria-hidden="true">↗</span></a></div><ol class="preview-steps">${[['Conocerte','Reconocer lo que importa para ti.'],['Interpretar','Relacionarlo con tu experiencia.'],['Explorar','Comparar caminos posibles.'],['Probar y decidir','Dar un paso y aprender de él.']].map(([title,text],i)=>`<li><span class="preview-number">0${i+1}</span><h3>${title}</h3><p>${text}</p></li>`).join('')}</ol></section>
      ${closing()}</div>`;
  }
  function accompaniment(id,icon) {
    const s=services.find(s=>s.id===id);
    if(!s)return `<div class="container page"><div class="page-intro"><div><p class="eyebrow">Acompañamientos</p><h1>Un acompañamiento<br>para cada etapa.</h1><p class="lead">Desde la primera elección de carrera hasta un cambio profesional: empieza por la situación que estás viviendo.</p></div><img src="assets/paths.webp" alt="" width="1536" height="1024"></div><div class="grid-3 section">${serviceCards(icon)}</div>${closing()}</div>`;
    return `<div class="container page"><div class="breadcrumb"><a href="#acompanamientos">Acompañamientos</a><span>/</span>${s.title}</div><div class="service-hero"><div><p class="eyebrow">${s.audience}</p><h1>${s.title}</h1><p class="lead">${s.intro}</p><div class="actions"><a class="btn" href="#primer-paso/${s.id}">Preparar mi siguiente paso <span aria-hidden="true">↗</span></a><a class="text-link" href="#proceso">Cómo funciona</a></div></div><img src="assets/${s.id==='elegir-carrera'?'hero':'paths'}.webp" alt="" width="1536" height="1024"></div><section class="section grid-2"><article class="panel"><p class="eyebrow">La pregunta de partida</p><h2>${s.question}</h2><p class="muted">${s.example}</p></article><article class="panel"><h2>Qué podemos explorar</h2><ul class="check-list">${s.items.map(t=>`<li>${icon('check')}<span>${t}</span></li>`).join('')}</ul></article></section><section class="help-band"><div><p class="eyebrow">Del mapa a la experiencia</p><h3>Una hipótesis que puedas probar</h3><p>${s.action}</p></div><a class="btn secondary small" href="#recursos/siguiente-paso">Preparar una experiencia</a></section>${closing()}</div>`;
  }
  function process() {
    return `<div class="container page"><div class="reading-intro"><p class="eyebrow">El proceso</p><h1>Aprender a elegir<br>te acompaña toda la vida.</h1><p class="lead">Tu historia, tus experiencias y tus circunstancias importan. El objetivo es que entiendas tus opciones y puedas tomar decisiones con cada vez más autonomía.</p></div><section class="journey-strip" aria-label="Momentos de una trayectoria"><p>Aprender a elegir te acompaña toda la vida.</p><ol>${['Autoconocimiento','Elección','Desarrollo','Experiencia profesional','Reorientación'].map(t=>`<li>${t}</li>`).join('')}</ol></section>${steps()}<section class="section grid-2"><article class="panel"><h2>Lo que sabes hacer y lo que quieres sostener.</h2><p class="muted">Puedes ser bueno en algo sin querer dedicarte a ello toda tu vida. Buscamos distinguir lo que disfrutas, lo que aprendiste a hacer, lo que haces por obligación y lo que te da energía.</p></article><article class="panel"><h2>La claridad también se practica.</h2><p class="muted">El proceso busca terminar en acciones: investigar opciones, hablar con profesionistas, tomar un curso, probar un proyecto o buscar una práctica. Después vuelves a lo aprendido y ajustas tu camino.</p></article></section><section class="section"><p class="eyebrow">Un recorrido al que puedes volver</p><h2>Antes, durante y después de la universidad.</h2><p class="lead">Elegir, desarrollarte y replantear tu trayectoria son momentos diferentes. Las preguntas de autoconocimiento pueden acompañarte en cada uno.</p><a class="text-link" href="#acompanamientos">Conocer los acompañamientos ↗</a></section>${closing()}</div>`;
  }
  function methodology() {
    return `<div class="container page prose"><p class="eyebrow">La metodología</p><h1>Herramientas para comprenderte.<br>Conversación para darles sentido.</h1><p class="lead">La propuesta combina modelos de autoconocimiento con tu historia, tus intereses, valores, motivaciones, habilidades y contexto. Ningún resultado se interpreta por separado de tu vida.</p><h2>Estilos de pensamiento y Benziger</h2><p>El modelo de estilos de pensamiento de Benziger forma parte del enfoque propuesto como herramienta de reflexión sobre preferencias. En este proyecto no se presenta como una radiografía del cerebro, una medida de actividad cerebral ni una predicción absoluta de comportamiento.</p><p>La aplicación de un instrumento formal deberá realizarse conforme a sus condiciones de uso y con una interpretación adecuada. Las guías de reflexión que puedes explorar en esta página son originales y demostrativas: <strong>no son la evaluación oficial de Benziger</strong>.</p><h2>Una mirada que integra distintas dimensiones</h2><p>Intereses, valores, motivación, fortalezas, formas de aprender, necesidad de autonomía o estructura, interacción social y ambientes de trabajo. También observamos experiencias concretas que generan energía o desgaste.</p><h2>Preferencias, habilidades y contexto</h2><p>El proceso distingue aquello que prefieres de aquello que has aprendido a hacer bien. Las preferencias son un punto de partida. Las habilidades pueden desarrollarse, y los intereses, las circunstancias y las formas de actuar pueden cambiar.</p><h2>Una hipótesis necesita experiencia</h2><p>Relacionamos el mapa personal con alternativas académicas y profesionales. Las experiencias —conversaciones, cursos, prácticas o proyectos— ayudan a contrastar lo que imaginas con lo que ocurre al hacerlo.</p><details class="technical-details"><summary>Cómo funcionan las guías demostrativas de esta web</summary><p>Las tres guías usan enunciados originales y respuestas de 1 a 5. El resultado es un promedio por dimensión; los enunciados inversos de personalidad se puntúan como 6 menos la respuesta. Se requieren todas las respuestas para finalizar.</p><p>No cuentan con validación psicométrica. Un promedio no es un percentil, una medida de capacidad ni una compatibilidad profesional calculada. Las áreas y actividades sugeridas son ejemplos para investigar.</p><p>No son evaluaciones BTSA o HBDI, instrumentos estandarizados basados en los Cinco Grandes ni herramientas de O*NET. Los ejercicios no sustituyen el acompañamiento o una evaluación formal.</p><a class="text-link" href="#evaluaciones">Explorar las guías de reflexión</a></details><div class="note">Tus respuestas a las guías se procesan en tu navegador. <a class="text-link" href="#privacidad">Conoce cómo se guardan</a>.</div><div class="actions" style="margin-top:28px"><a class="btn" href="#proceso">Conocer el proceso</a></div></div>`;
  }
  function faqPage() {
    return `<div class="container page"><div class="reading-intro"><p class="eyebrow">Resolvamos tus dudas</p><h1>Preguntas frecuentes</h1><p class="lead">Qué puedes esperar del acompañamiento, cómo interpretar un perfil y para qué sirven las guías de reflexión.</p></div>${faq()}<div class="actions"><a class="text-link" href="#metodologia">Conocer la metodología ↗</a><a class="text-link" href="#proceso">Ver el proceso ↗</a></div>${closing()}</div>`;
  }
  function about() {
    const p=settings.provider;
    return `<div class="container page"><div class="about-grid"><div class="about-art"><img src="assets/hero.webp" alt="Ilustración de una persona ante distintos caminos; no es un retrato del orientador." width="1536" height="1024"><p class="small muted">Una trayectoria se construye con decisiones, experiencias y nuevas preguntas.</p></div><article><p class="eyebrow">${p.name?'Sobre mí':'El propósito de este espacio'}</p><h1>${p.name?esc(p.name):'Comprender a la persona.<br>Acompañar sus decisiones.'}</h1><p class="lead">${p.bio?esc(p.bio):'La intención de este proyecto es ayudarte a reconocer patrones en tu vida y convertir ese conocimiento en decisiones con mayor sentido.'}</p><p class="muted">Tu historia tiene más valor que una etiqueta. El acompañamiento busca darte un método para explorar caminos y decidir con autonomía, también cuando aparezcan nuevas preguntas.</p>${p.name?`<h2>Formación y preparación</h2><ul class="credentials">${p.credentials.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:'<div class="note"><strong>El perfil del orientador se publicará aquí.</strong><br>Aquí podrás conocer a la persona que brindará el acompañamiento y consultar su formación. Esta información todavía está por confirmarse.</div>'}<a class="text-link" href="#metodologia">Conocer el enfoque de trabajo ↗</a></article></div></div>`;
  }
  function firstStep(icon, id) {
    const selected=services.find(service=>service.id===id);
    if(!selected)return `<div class="container page start-page"><div class="reading-intro"><p class="eyebrow">Tu primer paso</p><h1>Empecemos por<br>donde estás.</h1><p class="lead">Elige el momento que más se acerque a lo que estás viviendo. Te mostraremos qué puedes explorar y cómo comenzar.</p></div><div class="grid-3">${momentCards(icon,true)}</div><div class="start-reassurance">${icon('check')}<p>No necesitas registrarte ni tener una decisión tomada.</p></div><div class="start-help"><h2>¿Todavía no lo tienes claro?</h2><p class="muted">Conocer el proceso puede ayudarte a ordenar tus preguntas.</p><a class="text-link" href="#proceso">Ver cómo funciona <span aria-hidden="true">↗</span></a></div></div>`;
    const guide=selected.id==='elegir-carrera'?'intereses':'pensamiento';
    const url=settings.contact.url;
    const active=/^https:\/\//i.test(url);
    return `<div class="container page start-detail"><div class="breadcrumb"><a href="#primer-paso">Elegir otro momento</a><span>/</span>Tu punto de partida</div><div class="reading-intro"><p class="eyebrow">${selected.audience}</p><h1>${selected.title}</h1><p class="lead">${selected.intro}</p></div><div class="start-grid"><section class="panel next-step-panel"><p class="eyebrow">Para empezar</p><h2>${selected.question}</h2><p class="muted">${selected.action}</p><div class="actions"><a class="btn" href="#recursos/siguiente-paso">Preparar una experiencia <span aria-hidden="true">↗</span></a><a class="text-link" href="${link(selected)}">Ver el acompañamiento</a></div><div class="start-guide"><h3>También puedes explorar por tu cuenta.</h3><p>Una guía de reflexión puede ayudarte a formular tus primeras preguntas.</p><a class="text-link" href="#evaluacion/${guide}">Conocer la guía <span aria-hidden="true">↗</span></a><p class="small muted">Es un ejercicio demostrativo. No determina tu carrera.</p></div></section><aside class="conversation-panel"><p class="eyebrow">Prepara tu conversación</p><h2>Tres preguntas para ti.</h2><ol class="conversation-prompts"><li>¿Qué decisión quiero tomar?</li><li>¿Qué he probado y qué aprendí?</li><li>¿Qué necesito comprender mejor de mí?</li></ol><p class="small muted">Puedes anotarlas para ti. No tienes que compartir datos personales aquí.</p><div class="contact-status"><h3>${active?'Hablemos de tu momento.':'Acompañamiento personal'}</h3><p class="small muted">${active?'Consulta la disponibilidad y los detalles del servicio por este canal.':'El canal de atención todavía no está disponible. Por ahora puedes conocer el enfoque y explorar los recursos.'}</p>${active?`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(settings.contact.label)}</a>`:'<a class="text-link" href="#recursos">Ver recursos <span aria-hidden="true">↗</span></a>'}</div></aside></div></div>`;
  }
  return {settings,home,accompaniment,process,methodology,faqPage,about,firstStep};
})();
